<?php

return [
    'unique_percent' => env('ARTICLE_UNIQUE_PERCENT', 95),
    'shingle_length' => env('ARTICLE_SHINGLE_LENGTH', 1),
    'stop_symbols' => [".", ",", "!", "?", ":", ";", "-", "n", "r", "(", ")"],
    'stop_words' => ["a", "a's", "able", "about", "above", "according", "accordingly", "across", "actually", "after", "afterwards", "again", "against", "ain't", "all", "allow", "allows", "almost", "alone", "along", "already", "also", "although", "always", "am", "among", "amongst", "an", "and", "another", "any", "anybody", "anyhow", "anyone", "anything", "anyway", "anyways", "anywhere", "apart", "appear", "appreciate", "appropriate", "are", "aren't", "around", "as", "aside", "ask", "asking", "associated", "at", "available", "away", "awfully", "b", "be", "became", "because", "become", "becomes", "becoming", "been", "before", "beforehand", "behind", "being", "believe", "below", "beside", "besides", "best", "better", "between", "beyond", "both", "brief", "but", "by", "c", "c'mon", "c's", "came", "can", "can't", "cannot", "cant", "cause", "causes", "certain", "certainly", "changes", "clearly", "co", "com", "come", "comes", "concerning", "consequently", "consider", "considering", "contain", "containing", "contains", "corresponding", "could", "couldn't", "course", "currently", "d", "definitely", "described", "despite", "did", "didn't", "different", "do", "does", "doesn't", "doing", "don't", "done", "down", "downwards", "during", "e", "each", "edu", "eg", "eight", "either", "else", "elsewhere", "enough", "entirely", "especially", "et", "etc", "even", "ever", "every", "everybody", "everyone", "everything", "everywhere", "ex", "exactly", "example", "except", "f", "far", "few", "fifth", "first", "five", "followed", "following", "follows", "for", "former", "formerly", "forth", "four", "from", "further", "furthermore", "g", "get", "gets", "getting", "given", "gives", "go", "goes", "going", "gone", "got", "gotten", "greetings", "h", "had", "hadn't", "happens", "hardly", "has", "hasn't", "have", "haven't", "having", "he", "he's", "hello", "help", "hence", "her", "here", "here's", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "hi", "him", "himself", "his", "hither", "hopefully", "how", "howbeit", "however", "i", "i'd", "i'll", "i'm", "i've", "ie", "if", "ignored", "immediate", "in", "inasmuch", "inc", "indeed", "indicate", "indicated", "indicates", "inner", "insofar", "instead", "into", "inward", "is", "isn't", "it", "it'd", "it'll", "it's", "its", "itself", "j", "just", "k", "keep", "keeps", "kept", "know", "known", "knows", "l", "last", "lately", "later", "latter", "latterly", "least", "less", "lest", "let", "let's", "like", "liked", "likely", "little", "look", "looking", "looks", "ltd", "m", "mainly", "many", "may", "maybe", "me", "mean", "meanwhile", "merely", "might", "more", "moreover", "most", "mostly", "much", "must", "my", "myself", "n", "name", "namely", "nd", "near", "nearly", "necessary", "need", "needs", "neither", "never", "nevertheless", "new", "next", "nine", "no", "nobody", "non", "none", "noone", "nor", "normally", "not", "nothing", "novel", "now", "nowhere", "o", "obviously", "of", "off", "often", "oh", "ok", "okay", "old", "on", "once", "one", "ones", "only", "onto", "or", "other", "others", "otherwise", "ought", "our", "ours", "ourselves", "out", "outside", "over", "overall", "own", "p", "particular", "particularly", "per", "perhaps", "placed", "please", "plus", "possible", "presumably", "probably", "provides", "q", "que", "quite", "qv", "r", "rather", "rd", "re", "really", "reasonably", "regarding", "regardless", "regards", "relatively", "respectively", "right", "s", "said", "same", "saw", "say", "saying", "says", "second", "secondly", "see", "seeing", "seem", "seemed", "seeming", "seems", "seen", "self", "selves", "sensible", "sent", "serious", "seriously", "seven", "several", "shall", "she", "should", "shouldn't", "since", "six", "so", "some", "somebody", "somehow", "someone", "something", "sometime", "sometimes", "somewhat", "somewhere", "soon", "sorry", "specified", "specify", "specifying", "still", "sub", "such", "sup", "sure", "t", "t's", "take", "taken", "tell", "tends", "th", "than", "thank", "thanks", "thanx", "that", "that's", "thats", "the", "their", "theirs", "them", "themselves", "then", "thence", "there", "there's", "thereafter", "thereby", "therefore", "therein", "theres", "thereupon", "these", "they", "they'd", "they'll", "they're", "they've", "think", "third", "this", "thorough", "thoroughly", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "took", "toward", "towards", "tried", "tries", "truly", "try", "trying", "twice", "two", "u", "un", "under", "unfortunately", "unless", "unlikely", "until", "unto", "up", "upon", "us", "use", "used", "useful", "uses", "using", "usually", "uucp", "v", "value", "various", "very", "via", "viz", "vs", "w", "want", "wants", "was", "wasn't", "way", "we", "we'd", "we'll", "we're", "we've", "welcome", "well", "went", "were", "weren't", "what", "what's", "whatever", "when", "whence", "whenever", "where", "where's", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "who's", "whoever", "whole", "whom", "whose", "why", "will", "willing", "wish", "with", "within", "without", "won't", "wonder", "would", "wouldn't", "x", "y", "yes", "yet", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves", "z", "zero"],
    'irregular_verbs' => [
        [
            'arise',
            'arose',
            'arisen',
        ],
        [
            'awake',
            'awoke',
            'awaked',
        ],
        [
            'be',
            'is',
            'was',
            'were',
            'been',
        ],
        [
            'bear',
            'bore',
            'borne',
        ],
        [
            'become',
            'became',
            'become',
        ],
        [
            'begin',
            'began',
            'begun',
        ],
        [
            'bend',
            'bent',
            'bent',
        ],
        [
            'bind',
            'bound',
            'bound',
        ],
        [
            'bite',
            'bit',
            'bitten',
        ],
        [
            'bleed',
            'bled',
            'bled',
        ],
        [
            'blow',
            'blew',
            'blown',
        ],
        [
            'break',
            'broke',
            'broken',
        ],
        [
            'breed',
            'bred',
            'bred',
        ],
        [
            'bring',
            'brought',
            'brought',
        ],
        [
            'broadcast',
            'broadcast',
            'broadcast',
        ],
        [
            'build',
            'built',
            'built',
        ],
        [
            'burn',
            'burnt',
            'burnt',
        ],
        [
            'burst',
            'burst',
            'burst',
        ],
        [
            'buy',
            'bought',
            'bought',
        ],
        [
            'cast',
            'cast',
            'cast',
        ],
        [
            'catch',
            'caught',
            'caught',
        ],
        [
            'choose',
            'chose',
            'chosen',
        ],
        [
            'cling',
            'clung',
            'clung',
        ],
        [
            'come',
            'came',
            'come',
        ],
        [
            'cost',
            'cost',
            'cost',
        ],
        [
            'creep',
            'crept',
            'crept',
        ],
        [
            'cut',
            'cut',
            'cut',
        ],
        [
            'deal',
            'dealt',
            'dealt',
        ],
        [
            'dig',
            'dug',
            'dug',
        ],
        [
            'do',
            'did',
            'done',
        ],
        [
            'draw',
            'drew',
            'drawn',
        ],
        [
            'dream',
            'dreamt',
            'dreamt',
        ],
        [
            'drink',
            'drank',
            'drunk',
        ],
        [
            'drive',
            'drove',
            'driven',
        ],
        [
            'dwell',
            'dwelt',
            'dwelt',
        ],
        [
            'eat',
            'ate',
            'eaten',
        ],
        [
            'fall',
            'fell',
            'fallen',
        ],
        [
            'feed',
            'fed',
            'fed',
        ],
        [
            'feel',
            'felt',
            'felt',
        ],
        [
            'fight',
            'fought',
            'fought',
        ],
        [
            'find',
            'found',
            'found',
        ],
        [
            'flee',
            'fled',
            'fled',
        ],
        [
            'fling',
            'flung',
            'flung',
        ],
        [
            'fly',
            'flew',
            'flown',
        ],
        [
            'forbid',
            'forbade',
            'forbidden',
        ],
        [
            'forecast',
            'forecast',
            'forecast',
        ],
        [
            'forget',
            'forgot',
            'forgotten',
        ],
        [
            'forgive',
            'forgave',
            'forgiven',
        ],
        [
            'forsake',
            'forsook',
            'forsaken',
        ],
        [
            'freeze',
            'froze',
            'frozen',
        ],
        [
            'get',
            'got',
            'got',
        ],
        [
            'give',
            'gave',
            'given',
        ],
        [
            'go',
            'went',
            'gone',
        ],
        [
            'grind',
            'ground',
            'ground',
        ],
        [
            'grow',
            'grew',
            'grown',
        ],
        [
            'hang',
            'hung',
            'hung',
        ],
        [
            'have',
            'has',
            'had',
            'had',
        ],
        [
            'hear',
            'heard',
            'heard',
        ],
        [
            'hide',
            'hid',
            'hidden',
        ],
        [
            'hit',
            'hit',
            'hit',
        ],
        [
            'hold',
            'held',
            'held',
        ],
        [
            'hurt',
            'hurt',
            'hurt',
        ],
        [
            'keep',
            'kept',
            'kept',
        ],
        [
            'kneel',
            'knelt',
            'knelt',
        ],
        [
            'know',
            'knew',
            'known',
        ],
        [
            'lay',
            'laid',
            'laid',
        ],
        [
            'lead',
            'led',
            'led',
        ],
        [
            'lean',
            'leant',
            'leant',
        ],
        [
            'leap',
            'leapt',
            'leapt',
        ],
        [
            'learn',
            'learnt',
            'learnt',
        ],
        [
            'leave',
            'left',
            'left',
        ],
        [
            'lend',
            'lent',
            'lent',
        ],
        [
            'let',
            'let',
            'let',
        ],
        [
            'lie',
            'lay',
            'lain',
        ],
        [
            'light',
            'lit',
            'lit',
        ],
        [
            'lose',
            'lost',
            'lost',
        ],
        [
            'make',
            'made',
            'made',
        ],
        [
            'mean',
            'meant',
            'meant',
        ],
        [
            'meet',
            'met',
            'met',
        ],
        [
            'pay',
            'paid',
            'paid',
        ],
        [
            'put',
            'put',
            'put',
        ],
        [
            'read',
            'read',
            'read',
        ],
        [
            'ride',
            'rode',
            'ridden',
        ],
        [
            'ring',
            'rang',
            'rung',
        ],
        [
            'rise',
            'rose',
            'risen',
        ],
        [
            'run',
            'ran',
            'run',
        ],
        [
            'say',
            'said',
            'said',
        ],
        [
            'see',
            'saw',
            'seen',
        ],
        [
            'seek',
            'sought',
            'sought',
        ],
        [
            'sell',
            'sold',
            'sold',
        ],
        [
            'send',
            'sent',
            'sent',
        ],
        [
            'set',
            'set',
            'set',
        ],
        [
            'sew',
            'sewed',
            'sewn',
        ],
        [
            'shake',
            'shook',
            'shaken',
        ],
        [
            'shed',
            'shed',
            'shed',
        ],
        [
            'shine',
            'shone',
            'shone',
        ],
        [
            'shoot',
            'shot',
            'shot',
        ],
        [
            'show',
            'showed',
            'shown',
        ],
        [
            'shrink',
            'shrank',
            'shrunk',
        ],
        [
            'shut',
            'shut',
            'shut',
        ],
        [
            'sing',
            'sang',
            'sung',
        ],
        [
            'sink',
            'sank',
            'sunk',
        ],
        [
            'sit',
            'sat',
            'sat',
        ],
        [
            'sleep',
            'slept',
            'slept',
        ],
        [
            'slide',
            'slid',
            'slid',
        ],
        [
            'sling',
            'slung',
            'slung',
        ],
        [
            'slink',
            'slunk',
            'slunk',
        ],
        [
            'slit',
            'slit',
            'slit',
        ],
        [
            'smell',
            'smelt',
            'smelt',
        ],
        [
            'sow',
            'sowed',
            'sown',
        ],
        [
            'speak',
            'spoke',
            'spoken',
        ],
        [
            'speed',
            'sped',
            'sped',
        ],
        [
            'spell',
            'spelt',
            'spelt',
        ],
        [
            'spend',
            'spent',
            'spent',
        ],
        [
            'spill',
            'spilt',
            'spilt',
        ],
        [
            'spin',
            'span',
            'spun',
        ],
        [
            'spit',
            'spat',
            'spat',
        ],
        [
            'split',
            'split',
            'split',
        ],
        [
            'spoil',
            'spoilt',
            'spoilt',
        ],
        [
            'spread',
            'spread',
            'spread',
        ],
        [
            'spring',
            'sprang',
            'sprung',
        ],
        [
            'stand',
            'stood',
            'stood',
        ],
        [
            'steal',
            'stole',
            'stolen',
        ],
        [
            'stick',
            'stuck',
            'stuck',
        ],
        [
            'sting',
            'stung',
            'stung',
        ],
        [
            'stink',
            'stank',
            'stunk',
        ],
        [
            'strew',
            'strewed',
            'strewn',
        ],
        [
            'stride',
            'strode',
            'stridden',
        ],
        [
            'strike',
            'struck',
            'struck',
        ],
        [
            'strive',
            'strove',
            'striven',
        ],
        [
            'swear',
            'swore',
            'sworn',
        ],
        [
            'sweep',
            'swept',
            'swept',
        ],
        [
            'swell',
            'swelled',
            'swollen',
        ],
        [
            'swim',
            'swam',
            'swum',
        ],
        [
            'swing',
            'swung',
            'swung',
        ],
        [
            'take',
            'took',
            'taken',
        ],
        [
            'teach',
            'taught',
            'taught',
        ],
        [
            'tear',
            'tore',
            'torn',
        ],
        [
            'tell',
            'told',
            'told',
        ],
        [
            'think',
            'thought',
            'thought',
        ],
        [
            'thrive',
            'throve',
            'thriven',
        ],
        [
            'throw',
            'threw',
            'thrown',
        ],
        [
            'thrust',
            'thrust',
            'thrust',
        ],
        [
            'tread',
            'trod',
            'trodden',
        ],
        [
            'understand',
            'understood',
            'understood',
        ],
        [
            'wake',
            'woke',
            'woken',
        ],
        [
            'wear',
            'wore',
            'worn',
        ],
        [
            'weave',
            'wove',
            'woven',
        ],
        [
            'weep',
            'wept',
            'wept',
        ],
        [
            'win',
            'won',
            'won',
        ],
        [
            'wind',
            'wound',
            'wound',
        ],
        [
            'wring',
            'wrung',
            'wrung',
        ],
        [
            'write',
            'wrote',
            'written',
        ],
    ],
];
